apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ include "node-3tier.fullname" . }}-backend-config
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false