apiVersion: v1
kind: Service
metadata:
  name: pg-exporter
  labels:
{{ include "node-3tier.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9187
      targetPort: 9187
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "node-3tier.name" . }}-db-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
