apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-3tier.fullname" . }}-web
  labels:
{{ include "node-3tier.labels" . | indent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"{{ include "node-3tier.fullname" . }}-backend-config"}}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "node-3tier.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
