FROM docker:dind
MAINTAINER virgil.chereches@gmail.com
WORKDIR /usr/local/bin
RUN wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
RUN unzip /tmp/terraform.zip

